apiVersion: v1
kind: ServiceAccount
metadata:
  name: piper
  namespace: piper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: piper-job-launcher
  namespace: piper
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: piper-job-launcher
  namespace: piper
subjects:
  - kind: ServiceAccount
    name: piper
    namespace: piper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: piper-job-launcher
