apiVersion: v1
kind: Secret
metadata:
  name: piper-s3
  namespace: piper
type: Opaque
stringData:
  endpoint: minio.default.svc.cluster.local:9000
  access_key: replace-me
  secret_key: replace-me
  bucket: piper
