version: 4

worker:
  master_url: http://localhost:8080
  state_dir: ./piper-worker-state/notebook
  baremetal: {}
  capabilities:
    notebook:
      notebooks_root: ./notebooks
      port_range: 8888-9900
