// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Response
	//	*WorkerMessage_Push
	//	*WorkerMessage_ProxyData
	//	*WorkerMessage_ProxyClose
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetResponse() *RPCResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *WorkerMessage) GetPush() *StatusPush {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *WorkerMessage) GetProxyData() *ProxyData {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ProxyData); ok {
			return x.ProxyData
		}
	}
	return nil
}

func (x *WorkerMessage) GetProxyClose() *ProxyClose {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_ProxyClose); ok {
			return x.ProxyClose
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Register struct {
	Register *Registration `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Response struct {
	Response *RPCResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type WorkerMessage_Push struct {
	Push *StatusPush `protobuf:"bytes,3,opt,name=push,proto3,oneof"`
}

type WorkerMessage_ProxyData struct {
	ProxyData *ProxyData `protobuf:"bytes,4,opt,name=proxy_data,json=proxyData,proto3,oneof"` // raw bytes: target → master (notebook HTTP/WS)
}

type WorkerMessage_ProxyClose struct {
	ProxyClose *ProxyClose `protobuf:"bytes,5,opt,name=proxy_close,json=proxyClose,proto3,oneof"` // target connection closed or errored
}

func (*WorkerMessage_Register) isWorkerMessage_Payload() {}

func (*WorkerMessage_Response) isWorkerMessage_Payload() {}

func (*WorkerMessage_Push) isWorkerMessage_Payload() {}

func (*WorkerMessage_ProxyData) isWorkerMessage_Payload() {}

func (*WorkerMessage_ProxyClose) isWorkerMessage_Payload() {}

// Registration is the first message sent by a worker after connecting.
type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "baremetal" | "k8s"
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Gpus          []string               `protobuf:"bytes,4,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // "notebook" | "serving" | "pipeline"
	ClusterName   string                 `protobuf:"bytes,6,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Registration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Registration) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Registration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Registration) GetGpus() []string {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Registration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Registration) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Registration) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// RPCResponse carries the result (or error) for a MasterMessage command.
type RPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded result struct; empty on void methods
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RPCResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RPCResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StatusPush is an async notification from worker to master.
// Replaces the old HTTP PATCH /api/notebooks/:name/status callback.
type StatusPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`   // e.g. "notebook.status_update"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded domain-specific struct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusPush) Reset() {
	*x = StatusPush{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusPush) ProtoMessage() {}

func (x *StatusPush) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusPush.ProtoReflect.Descriptor instead.
func (*StatusPush) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusPush) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StatusPush) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MasterMessage_RpcCmd
	//	*MasterMessage_ProxyOpen
	//	*MasterMessage_ProxyData
	//	*MasterMessage_ProxyClose
	Payload       isMasterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *MasterMessage) GetPayload() isMasterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MasterMessage) GetRpcCmd() *RPCCommand {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_RpcCmd); ok {
			return x.RpcCmd
		}
	}
	return nil
}

func (x *MasterMessage) GetProxyOpen() *ProxyOpen {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_ProxyOpen); ok {
			return x.ProxyOpen
		}
	}
	return nil
}

func (x *MasterMessage) GetProxyData() *ProxyData {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_ProxyData); ok {
			return x.ProxyData
		}
	}
	return nil
}

func (x *MasterMessage) GetProxyClose() *ProxyClose {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_ProxyClose); ok {
			return x.ProxyClose
		}
	}
	return nil
}

type isMasterMessage_Payload interface {
	isMasterMessage_Payload()
}

type MasterMessage_RpcCmd struct {
	RpcCmd *RPCCommand `protobuf:"bytes,1,opt,name=rpc_cmd,json=rpcCmd,proto3,oneof"` // existing RPC dispatch
}

type MasterMessage_ProxyOpen struct {
	ProxyOpen *ProxyOpen `protobuf:"bytes,2,opt,name=proxy_open,json=proxyOpen,proto3,oneof"` // open TCP channel to target (notebook pod)
}

type MasterMessage_ProxyData struct {
	ProxyData *ProxyData `protobuf:"bytes,3,opt,name=proxy_data,json=proxyData,proto3,oneof"` // raw bytes: browser → target
}

type MasterMessage_ProxyClose struct {
	ProxyClose *ProxyClose `protobuf:"bytes,4,opt,name=proxy_close,json=proxyClose,proto3,oneof"` // close channel
}

func (*MasterMessage_RpcCmd) isMasterMessage_Payload() {}

func (*MasterMessage_ProxyOpen) isMasterMessage_Payload() {}

func (*MasterMessage_ProxyData) isMasterMessage_Payload() {}

func (*MasterMessage_ProxyClose) isMasterMessage_Payload() {}

// RPCCommand dispatches a single RPC call to the worker.
type RPCCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlated with RPCResponse.request_id
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                        // e.g. "notebook.start", "serving.deploy"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // JSON-encoded request struct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCCommand) Reset() {
	*x = RPCCommand{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCCommand) ProtoMessage() {}

func (x *RPCCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCCommand.ProtoReflect.Descriptor instead.
func (*RPCCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RPCCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RPCCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPCCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ProxyOpen requests the worker to open a TCP connection to target.
type ProxyOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // unique per proxy session (UUID)
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                        // "host:port", e.g. "piper-nb-mynotebook.default.svc:8888"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyOpen) Reset() {
	*x = ProxyOpen{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyOpen) ProtoMessage() {}

func (x *ProxyOpen) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyOpen.ProtoReflect.Descriptor instead.
func (*ProxyOpen) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProxyOpen) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProxyOpen) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// ProxyData carries raw bytes for an open proxy channel.
type ProxyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyData) Reset() {
	*x = ProxyData{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyData) ProtoMessage() {}

func (x *ProxyData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyData.ProtoReflect.Descriptor instead.
func (*ProxyData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProxyData) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProxyData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ProxyClose signals that a proxy channel should be torn down.
type ProxyClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // non-empty if closed due to error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyClose) Reset() {
	*x = ProxyClose{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyClose) ProtoMessage() {}

func (x *ProxyClose) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyClose.ProtoReflect.Descriptor instead.
func (*ProxyClose) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyClose) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProxyClose) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0epiper.agent.v1\"\xbe\x02\n" +
	"\rWorkerMessage\x12:\n" +
	"\bregister\x18\x01 \x01(\v2\x1c.piper.agent.v1.RegistrationH\x00R\bregister\x129\n" +
	"\bresponse\x18\x02 \x01(\v2\x1b.piper.agent.v1.RPCResponseH\x00R\bresponse\x120\n" +
	"\x04push\x18\x03 \x01(\v2\x1a.piper.agent.v1.StatusPushH\x00R\x04push\x12:\n" +
	"\n" +
	"proxy_data\x18\x04 \x01(\v2\x19.piper.agent.v1.ProxyDataH\x00R\tproxyData\x12=\n" +
	"\vproxy_close\x18\x05 \x01(\v2\x1a.piper.agent.v1.ProxyCloseH\x00R\n" +
	"proxyCloseB\t\n" +
	"\apayload\"\xa6\x02\n" +
	"\fRegistration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x12\n" +
	"\x04gpus\x18\x04 \x03(\tR\x04gpus\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12!\n" +
	"\fcluster_name\x18\x06 \x01(\tR\vclusterName\x12@\n" +
	"\x06labels\x18\a \x03(\v2(.piper.agent.v1.Registration.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\vRPCResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\">\n" +
	"\n" +
	"StatusPush\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x88\x02\n" +
	"\rMasterMessage\x125\n" +
	"\arpc_cmd\x18\x01 \x01(\v2\x1a.piper.agent.v1.RPCCommandH\x00R\x06rpcCmd\x12:\n" +
	"\n" +
	"proxy_open\x18\x02 \x01(\v2\x19.piper.agent.v1.ProxyOpenH\x00R\tproxyOpen\x12:\n" +
	"\n" +
	"proxy_data\x18\x03 \x01(\v2\x19.piper.agent.v1.ProxyDataH\x00R\tproxyData\x12=\n" +
	"\vproxy_close\x18\x04 \x01(\v2\x1a.piper.agent.v1.ProxyCloseH\x00R\n" +
	"proxyCloseB\t\n" +
	"\apayload\"]\n" +
	"\n" +
	"RPCCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"B\n" +
	"\tProxyOpen\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\">\n" +
	"\tProxyData\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"A\n" +
	"\n" +
	"ProxyClose\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2[\n" +
	"\fAgentService\x12K\n" +
	"\aConnect\x12\x1d.piper.agent.v1.WorkerMessage\x1a\x1d.piper.agent.v1.MasterMessage(\x010\x01B)Z'github.com/piper/piper/internal/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*WorkerMessage)(nil), // 0: piper.agent.v1.WorkerMessage
	(*Registration)(nil),  // 1: piper.agent.v1.Registration
	(*RPCResponse)(nil),   // 2: piper.agent.v1.RPCResponse
	(*StatusPush)(nil),    // 3: piper.agent.v1.StatusPush
	(*MasterMessage)(nil), // 4: piper.agent.v1.MasterMessage
	(*RPCCommand)(nil),    // 5: piper.agent.v1.RPCCommand
	(*ProxyOpen)(nil),     // 6: piper.agent.v1.ProxyOpen
	(*ProxyData)(nil),     // 7: piper.agent.v1.ProxyData
	(*ProxyClose)(nil),    // 8: piper.agent.v1.ProxyClose
	nil,                   // 9: piper.agent.v1.Registration.LabelsEntry
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: piper.agent.v1.WorkerMessage.register:type_name -> piper.agent.v1.Registration
	2,  // 1: piper.agent.v1.WorkerMessage.response:type_name -> piper.agent.v1.RPCResponse
	3,  // 2: piper.agent.v1.WorkerMessage.push:type_name -> piper.agent.v1.StatusPush
	7,  // 3: piper.agent.v1.WorkerMessage.proxy_data:type_name -> piper.agent.v1.ProxyData
	8,  // 4: piper.agent.v1.WorkerMessage.proxy_close:type_name -> piper.agent.v1.ProxyClose
	9,  // 5: piper.agent.v1.Registration.labels:type_name -> piper.agent.v1.Registration.LabelsEntry
	5,  // 6: piper.agent.v1.MasterMessage.rpc_cmd:type_name -> piper.agent.v1.RPCCommand
	6,  // 7: piper.agent.v1.MasterMessage.proxy_open:type_name -> piper.agent.v1.ProxyOpen
	7,  // 8: piper.agent.v1.MasterMessage.proxy_data:type_name -> piper.agent.v1.ProxyData
	8,  // 9: piper.agent.v1.MasterMessage.proxy_close:type_name -> piper.agent.v1.ProxyClose
	0,  // 10: piper.agent.v1.AgentService.Connect:input_type -> piper.agent.v1.WorkerMessage
	4,  // 11: piper.agent.v1.AgentService.Connect:output_type -> piper.agent.v1.MasterMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Response)(nil),
		(*WorkerMessage_Push)(nil),
		(*WorkerMessage_ProxyData)(nil),
		(*WorkerMessage_ProxyClose)(nil),
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*MasterMessage_RpcCmd)(nil),
		(*MasterMessage_ProxyOpen)(nil),
		(*MasterMessage_ProxyData)(nil),
		(*MasterMessage_ProxyClose)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
