// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: member.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemberTunnelService_Connect_FullMethodName = "/piper.member.v1.MemberTunnelService/Connect"
)

// MemberTunnelServiceClient is the client API for MemberTunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemberTunnelService is the outbound tunnel a remote Member dials to reach
// its Home (fed.md §13.4). Unlike AgentService (proto/agent.proto), it never
// carries a generic-target proxy — a Home may only invoke the fixed set of
// memberclient.Client methods against an enrolled Member, never an
// arbitrary host:port. Message/service names are all Member-prefixed so
// this file can share agent.proto's generated Go package without symbol
// collisions.
//
// The Member dials Connect() and keeps the stream open for its lifetime.
// - First MemberMessage must be a MemberEnrollment (identifies the Member).
// - Home sends HomeMessage to invoke a memberclient.Client method.
// - Member replies with MemberRPCResponse per command.
type MemberTunnelServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MemberMessage, HomeMessage], error)
}

type memberTunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberTunnelServiceClient(cc grpc.ClientConnInterface) MemberTunnelServiceClient {
	return &memberTunnelServiceClient{cc}
}

func (c *memberTunnelServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MemberMessage, HomeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MemberTunnelService_ServiceDesc.Streams[0], MemberTunnelService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MemberMessage, HomeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemberTunnelService_ConnectClient = grpc.BidiStreamingClient[MemberMessage, HomeMessage]

// MemberTunnelServiceServer is the server API for MemberTunnelService service.
// All implementations must embed UnimplementedMemberTunnelServiceServer
// for forward compatibility.
//
// MemberTunnelService is the outbound tunnel a remote Member dials to reach
// its Home (fed.md §13.4). Unlike AgentService (proto/agent.proto), it never
// carries a generic-target proxy — a Home may only invoke the fixed set of
// memberclient.Client methods against an enrolled Member, never an
// arbitrary host:port. Message/service names are all Member-prefixed so
// this file can share agent.proto's generated Go package without symbol
// collisions.
//
// The Member dials Connect() and keeps the stream open for its lifetime.
// - First MemberMessage must be a MemberEnrollment (identifies the Member).
// - Home sends HomeMessage to invoke a memberclient.Client method.
// - Member replies with MemberRPCResponse per command.
type MemberTunnelServiceServer interface {
	Connect(grpc.BidiStreamingServer[MemberMessage, HomeMessage]) error
	mustEmbedUnimplementedMemberTunnelServiceServer()
}

// UnimplementedMemberTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberTunnelServiceServer struct{}

func (UnimplementedMemberTunnelServiceServer) Connect(grpc.BidiStreamingServer[MemberMessage, HomeMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMemberTunnelServiceServer) mustEmbedUnimplementedMemberTunnelServiceServer() {}
func (UnimplementedMemberTunnelServiceServer) testEmbeddedByValue()                             {}

// UnsafeMemberTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberTunnelServiceServer will
// result in compilation errors.
type UnsafeMemberTunnelServiceServer interface {
	mustEmbedUnimplementedMemberTunnelServiceServer()
}

func RegisterMemberTunnelServiceServer(s grpc.ServiceRegistrar, srv MemberTunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedMemberTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemberTunnelService_ServiceDesc, srv)
}

func _MemberTunnelService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MemberTunnelServiceServer).Connect(&grpc.GenericServerStream[MemberMessage, HomeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemberTunnelService_ConnectServer = grpc.BidiStreamingServer[MemberMessage, HomeMessage]

// MemberTunnelService_ServiceDesc is the grpc.ServiceDesc for MemberTunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberTunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "piper.member.v1.MemberTunnelService",
	HandlerType: (*MemberTunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _MemberTunnelService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "member.proto",
}
