// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: member.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MemberMessage_Enroll
	//	*MemberMessage_Response
	Payload       isMemberMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberMessage) Reset() {
	*x = MemberMessage{}
	mi := &file_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMessage) ProtoMessage() {}

func (x *MemberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMessage.ProtoReflect.Descriptor instead.
func (*MemberMessage) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberMessage) GetPayload() isMemberMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MemberMessage) GetEnroll() *MemberEnrollment {
	if x != nil {
		if x, ok := x.Payload.(*MemberMessage_Enroll); ok {
			return x.Enroll
		}
	}
	return nil
}

func (x *MemberMessage) GetResponse() *MemberRPCResponse {
	if x != nil {
		if x, ok := x.Payload.(*MemberMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isMemberMessage_Payload interface {
	isMemberMessage_Payload()
}

type MemberMessage_Enroll struct {
	Enroll *MemberEnrollment `protobuf:"bytes,1,opt,name=enroll,proto3,oneof"`
}

type MemberMessage_Response struct {
	Response *MemberRPCResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*MemberMessage_Enroll) isMemberMessage_Payload() {}

func (*MemberMessage_Response) isMemberMessage_Payload() {}

// MemberEnrollment is the first message a Member sends after connecting.
// token is a static per-Member shared secret configured on both sides.
// Rotation/revocation is deferred (fed.md §13.4 follow-up) — this proves
// the enrollment boundary, not a full credential lifecycle.
type MemberEnrollment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        string                 `protobuf:"bytes,1,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberEnrollment) Reset() {
	*x = MemberEnrollment{}
	mi := &file_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberEnrollment) ProtoMessage() {}

func (x *MemberEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberEnrollment.ProtoReflect.Descriptor instead.
func (*MemberEnrollment) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberEnrollment) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *MemberEnrollment) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *MemberEnrollment) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// MemberRPCResponse carries the result (or error) for a MemberRPCCommand.
type MemberRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded response DTO from internal/memberclient
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRPCResponse) Reset() {
	*x = MemberRPCResponse{}
	mi := &file_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRPCResponse) ProtoMessage() {}

func (x *MemberRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRPCResponse.ProtoReflect.Descriptor instead.
func (*MemberRPCResponse) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{2}
}

func (x *MemberRPCResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MemberRPCResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MemberRPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HomeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HomeMessage_RpcCmd
	Payload       isHomeMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeMessage) Reset() {
	*x = HomeMessage{}
	mi := &file_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeMessage) ProtoMessage() {}

func (x *HomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeMessage.ProtoReflect.Descriptor instead.
func (*HomeMessage) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{3}
}

func (x *HomeMessage) GetPayload() isHomeMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HomeMessage) GetRpcCmd() *MemberRPCCommand {
	if x != nil {
		if x, ok := x.Payload.(*HomeMessage_RpcCmd); ok {
			return x.RpcCmd
		}
	}
	return nil
}

type isHomeMessage_Payload interface {
	isHomeMessage_Payload()
}

type HomeMessage_RpcCmd struct {
	RpcCmd *MemberRPCCommand `protobuf:"bytes,1,opt,name=rpc_cmd,json=rpcCmd,proto3,oneof"`
}

func (*HomeMessage_RpcCmd) isHomeMessage_Payload() {}

// MemberRPCCommand invokes one memberclient.Client method on the Member.
type MemberRPCCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlated with MemberRPCResponse.request_id
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                        // e.g. "SubmitRun" — matches a memberclient.Client method 1:1
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // JSON-encoded request DTO from internal/memberclient
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRPCCommand) Reset() {
	*x = MemberRPCCommand{}
	mi := &file_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRPCCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRPCCommand) ProtoMessage() {}

func (x *MemberRPCCommand) ProtoReflect() protoreflect.Message {
	mi := &file_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRPCCommand.ProtoReflect.Descriptor instead.
func (*MemberRPCCommand) Descriptor() ([]byte, []int) {
	return file_member_proto_rawDescGZIP(), []int{4}
}

func (x *MemberRPCCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MemberRPCCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MemberRPCCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_member_proto protoreflect.FileDescriptor

const file_member_proto_rawDesc = "" +
	"\n" +
	"\fmember.proto\x12\x0fpiper.member.v1\"\x99\x01\n" +
	"\rMemberMessage\x12;\n" +
	"\x06enroll\x18\x01 \x01(\v2!.piper.member.v1.MemberEnrollmentH\x00R\x06enroll\x12@\n" +
	"\bresponse\x18\x02 \x01(\v2\".piper.member.v1.MemberRPCResponseH\x00R\bresponseB\t\n" +
	"\apayload\"^\n" +
	"\x10MemberEnrollment\x12\x17\n" +
	"\ahome_id\x18\x01 \x01(\tR\x06homeId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"b\n" +
	"\x11MemberRPCResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"V\n" +
	"\vHomeMessage\x12<\n" +
	"\arpc_cmd\x18\x01 \x01(\v2!.piper.member.v1.MemberRPCCommandH\x00R\x06rpcCmdB\t\n" +
	"\apayload\"c\n" +
	"\x10MemberRPCCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload2b\n" +
	"\x13MemberTunnelService\x12K\n" +
	"\aConnect\x12\x1e.piper.member.v1.MemberMessage\x1a\x1c.piper.member.v1.HomeMessage(\x010\x01B*Z(github.com/loykin/piper/internal/agentpbb\x06proto3"

var (
	file_member_proto_rawDescOnce sync.Once
	file_member_proto_rawDescData []byte
)

func file_member_proto_rawDescGZIP() []byte {
	file_member_proto_rawDescOnce.Do(func() {
		file_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)))
	})
	return file_member_proto_rawDescData
}

var file_member_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_member_proto_goTypes = []any{
	(*MemberMessage)(nil),     // 0: piper.member.v1.MemberMessage
	(*MemberEnrollment)(nil),  // 1: piper.member.v1.MemberEnrollment
	(*MemberRPCResponse)(nil), // 2: piper.member.v1.MemberRPCResponse
	(*HomeMessage)(nil),       // 3: piper.member.v1.HomeMessage
	(*MemberRPCCommand)(nil),  // 4: piper.member.v1.MemberRPCCommand
}
var file_member_proto_depIdxs = []int32{
	1, // 0: piper.member.v1.MemberMessage.enroll:type_name -> piper.member.v1.MemberEnrollment
	2, // 1: piper.member.v1.MemberMessage.response:type_name -> piper.member.v1.MemberRPCResponse
	4, // 2: piper.member.v1.HomeMessage.rpc_cmd:type_name -> piper.member.v1.MemberRPCCommand
	0, // 3: piper.member.v1.MemberTunnelService.Connect:input_type -> piper.member.v1.MemberMessage
	3, // 4: piper.member.v1.MemberTunnelService.Connect:output_type -> piper.member.v1.HomeMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_member_proto_init() }
func file_member_proto_init() {
	if File_member_proto != nil {
		return
	}
	file_member_proto_msgTypes[0].OneofWrappers = []any{
		(*MemberMessage_Enroll)(nil),
		(*MemberMessage_Response)(nil),
	}
	file_member_proto_msgTypes[3].OneofWrappers = []any{
		(*HomeMessage_RpcCmd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_member_proto_rawDesc), len(file_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_proto_goTypes,
		DependencyIndexes: file_member_proto_depIdxs,
		MessageInfos:      file_member_proto_msgTypes,
	}.Build()
	File_member_proto = out.File
	file_member_proto_goTypes = nil
	file_member_proto_depIdxs = nil
}
