apiVersion: piper/v1
kind: Pipeline

metadata:
  name: simple-test
  description: "Simple pipeline for local testing"

spec:
  steps:
  - name: hello
    run:
      type: command
      command: ["echo", "hello from piper"]

  - name: world
    run:
      type: command
      command: ["echo", "world!"]
    depends_on: [hello]
